apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: NodePort
